'use strict';

const fs = require('fs');
const path = require('path');

const { list, many, one, fail, escapeCell, escapeRegExp, globToRegExp, matches, gateName, firstExistingPath, formatList, existingPaths, parseDuration, expiryFromNow, titleCase, markdownTable, parseTomlSectionNames, parseTomlTableKeys, matchBracedDict, minimatchSimple, isTestSourceFile } = require('./helpers.cjs');
const { run, readFile, writeFile, readJson, writeJson, readJsonSafe, renderTemplate, ensureDir, skillDir, gitHead, shellQuote, safeFileName, relPath, rel, listStagedFiles, listWorktreeFiles, collectSourceFiles } = require('./io-utils.cjs');
const { collectGovernancePrograms, detectNestedProjectRoots, listContainsPyFiles, readProgramTreeMeta, detectProjectName, detectPythonPackageRoots, collectStewardPrograms } = require('./programs.cjs');
const { collectProjectInfo, collectFeatureCandidates, renderFeatureOverviewLines, splitEvidenceItems, collectEntrypointFeatureCandidates, collectPlannedFeatureCandidates, collectMarkdownCandidates, headingMatchesCandidateMode, cleanMarkdownText, isUsefulCandidateName, humanizeRouteFeatureName, isDynamicRouteSegment, cleanRouteSegment, featureKey, matchingFeatureKeyForCommand, uniqueCandidates, collectSourceTodoCandidates, renderCandidateEvidenceLines } = require('./scan-project.cjs');
function refreshFunctionTreeDoc(root) {
  const result = writeFunctionTreeDoc(root, {});
  const output = [
    result.changed ? `updated ${rel(root, result.docPath)}` : `${rel(root, result.docPath)} unchanged`,
  ];
  if (result.backupPath) output.push(`backup: ${rel(root, result.backupPath)}`);
  console.log(output.join('\n'));
}

function writeFunctionTreeDoc(root, context) {
  const gov = path.join(root, '.governance');
  ensureDir(gov);
  const docPath = path.join(root, 'FUNCTION_TREE.md');
  const existing = fs.existsSync(docPath) ? readFile(docPath) : '';
  const existingTreeBody = extractExistingFunctionTreeBody(existing);
  const notes = extractProjectNotes(existing);
  const content = renderFunctionTreeDoc(root, context, existingTreeBody, notes);
  if (existing === content) return { docPath, backupPath: '', changed: false };

  let backupPath = '';
  if (existing) {
    backupPath = backupFunctionTreeDoc(root, existing);
  }
  writeFile(docPath, content);
  return { docPath, backupPath, changed: true };
}

function backupFunctionTreeDoc(root, content) {
  const backupDir = path.join(root, '.governance', 'backups');
  ensureDir(backupDir);
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  let backupPath = path.join(backupDir, `FUNCTION_TREE.${stamp}.md`);
  let suffix = 1;
  while (fs.existsSync(backupPath)) {
    backupPath = path.join(backupDir, `FUNCTION_TREE.${stamp}.${suffix}.md`);
    suffix += 1;
  }
  writeFile(backupPath, content);
  return backupPath;
}

function extractProjectNotes(existing) {
  const match = existing.match(/<!-- function-tree:project-notes:start -->([\s\S]*?)<!-- function-tree:project-notes:end -->/);
  if (match) {
    const notes = match[1].trim();
    if (!notes || extractPreservedPreviousFunctionTree(notes)) return defaultProjectNotes();
    return notes;
  }
  return defaultProjectNotes();
}

function extractExistingFunctionTreeBody(existing) {
  if (!existing || !existing.trim()) return '';
  const preserved = extractPreservedPreviousFunctionTree(existing);
  if (preserved) return stripFunctionTreeTitle(preserved);

  const generated = existing.match(/<!-- function-tree:generated:start -->([\s\S]*?)<!-- function-tree:generated:end -->/);
  if (generated) {
    const body = stripGeneratedDocPreamble(generated[1]);
    if (looksLikeFunctionTreeBody(body) && !isRefreshableGeneratedFunctionTreeBody(body)) return body;
    return '';
  }

  const withoutGenerated = stripGeneratedFunctionTreeSection(existing)
    .replace(/<!-- function-tree:project-notes:start -->[\s\S]*?<!-- function-tree:project-notes:end -->/g, '')
    .trim();
  if (!withoutGenerated) return '';
  return stripFunctionTreeTitle(withoutGenerated);
}

function extractPreservedPreviousFunctionTree(value) {
  const marker = '## Preserved Previous FUNCTION_TREE.md Content';
  const index = value.indexOf(marker);
  if (index < 0) return '';
  const rest = value.slice(index + marker.length).trim();
  return rest.replace(/^The following content came from the pre-existing `FUNCTION_TREE\.md` before function-tree generated sections were added\.\s*/i, '').trim();
}

function stripGeneratedFunctionTreeSection(existing) {
  return existing.replace(/<!-- function-tree:generated:start -->[\s\S]*?<!-- function-tree:generated:end -->/g, '').trim();
}

function stripFunctionTreeTitle(value) {
  return String(value || '').trim().replace(/^#\s+FUNCTION_TREE\s*/i, '').trim();
}

function stripGeneratedDocPreamble(value) {
  return String(value || '')
    .trim()
    .replace(/^Generated by the `function-tree` skill\.[^\n]*\n+/i, '')
    .trim();
}

function looksLikeFunctionTreeBody(value) {
  return /##\s+(功能全景图|状态注册表|模块\/命令证据展开|模块依赖关系|Feature Map|Status Registry|Dependency Map)/i.test(String(value || ''));
}

function isRefreshableGeneratedFunctionTreeBody(value) {
  const body = String(value || '');
  return (
    /\|\s*Node\s*\|\s*Type\s*\|\s*Status\s*\|\s*Evidence\s*\/\s*Notes\s*\|/i.test(body) ||
    /Auto-discovered (existing feature|planned\/unfinished|source modules|project commands)/i.test(body) ||
    /Existing feature candidates:/.test(body) ||
    /Add README\/API\/product feature bullets/.test(body)
  );
}

function defaultProjectNotes() {
  return [
    '- Add project-specific architecture notes here.',
    '- Add local build, test, release, and compliance gates here.',
    '- Keep long-lived project conventions here; keep task state in `.governance/`.',
  ].join('\n');
}

function renderFunctionTreeDoc(root, context, existingTreeBody, notes) {
  const info = collectProjectInfo(root);
  const programs = collectGovernancePrograms(root, context);
  const programRows = programs.length ? programs.map((program) => [
    program.name,
    program.ref || '-',
    program.description || '-',
    String(program.nodeCount),
    String(program.activeCount),
    program.treePath,
  ]) : [['-', '-', '-', '0', '0', '-']];
  const treeBody = existingTreeBody && looksLikeFunctionTreeBody(existingTreeBody)
    ? existingTreeBody
    : renderDefaultFunctionTreeBody(root, context, info, programs, programRows);

  return [
    '# FUNCTION_TREE',
    '',
    '<!-- function-tree:generated:start -->',
    'Generated by the `function-tree` skill. Refresh this file with `ft-governance.cjs doc --root <repo>`.',
    '',
    treeBody,
    '<!-- function-tree:generated:end -->',
    '',
    '<!-- function-tree:project-notes:start -->',
    notes,
    '<!-- function-tree:project-notes:end -->',
    '',
  ].join('\n');
}

function renderDefaultFunctionTreeBody(root, context, info, programs, programRows) {
  const logProgram = context.program || (programs[0] && programs[0].name) || 'project-governance';
  const logRef = context.ref || (programs[0] && programs[0].ref) || 'unmapped';
  const featureRows = info.featureCandidates.length
    ? info.featureCandidates.map((feature) => `| ${escapeCell(feature.name)} | ${escapeCell(feature.type)} | ${escapeCell(feature.status)} | ${escapeCell(feature.evidence)}; ${escapeCell(feature.boundary)} |`)
    : ['| - | feature candidate | 待登记 | Add README/API/product feature bullets, then rerun `doc`. |'];
  const moduleRows = info.sourceModules.length
    ? info.sourceModules.map((module) => module.fileCount
      ? `| \`${module.path}\` | module dir | 待核验 | ${module.fileCount} source files; map to capability nodes after review. |`
      : `| \`${module.path}\` | module | 待核验 | Auto-discovered source module; map to a capability node after review. |`)
    : [];
  const sourceRows = info.sourceRoots.length
    ? info.sourceRoots.map((source) => `| \`${source}\` | source root | 待登记 | Map modules under this root into capability nodes. |`)
    : ['| - | source root | 待登记 | Add source roots after project structure is known. |'];
  const docRows = info.docs.length
    ? info.docs.map((doc) => `| \`${doc}\` | documentation | 已登记 | Use as evidence when mapping feature ownership. |`)
    : ['| - | documentation | 待登记 | Add architecture, API, or operation docs as evidence. |'];
  const commandRows = info.commandEntries.length
    ? info.commandEntries.map((command) => `| \`${command.command}\` | ${escapeCell(command.purpose)} | 待核验 | Evidence: \`${command.evidence}\` |`)
    : [];
  const uiRows = info.uiEntries.length
    ? info.uiEntries.map((entry) => `| \`${entry.route}\` | ${escapeCell(entry.source)} | 待核验 | Evidence: \`${entry.evidence}\` |`)
    : ['| - | UI route | 待登记 | Add frontend page files or router definitions to register UI entrypoints. |'];
  const apiRows = info.apiEntries.length
    ? info.apiEntries.map((entry) => `| \`${entry.method} ${entry.path}\` | ${escapeCell(entry.source)} | 待核验 | Evidence: \`${entry.evidence}\` |`)
    : ['| - | API route | 待登记 | Add OpenAPI specs or route definitions to register service/API entrypoints. |'];
  const publicApiRows = info.publicApiEntries && info.publicApiEntries.length
    ? info.publicApiEntries.map((entry) => `| \`${entry.module}\` | public API | 已登记 | ${entry.count} exports: ${entry.exports.slice(0, 8).join(', ')}${entry.count > 8 ? ', ...' : ''} (evidence: \`${entry.evidence}\`) |`)
    : ['| - | public API | 待登记 | Python packages with `__all__` or JS modules with named exports will be detected. |'];
  const docSystemRows = info.docSystemInfo && info.docSystemInfo.length
    ? info.docSystemInfo.map((entry) => `| ${escapeCell(entry.system)} | doc system | 已登记 | ${escapeCell(entry.detail)} (evidence: \`${entry.evidence}\`) |`)
    : ['| - | doc system | 待登记 | Sphinx, MkDocs, Docusaurus, and other doc systems will be auto-detected. |'];
  const exceptionRows = info.exceptionEntries && info.exceptionEntries.length
    ? info.exceptionEntries.map((entry) => `| \`${entry.name}\` | exception | 已登记 | extends \`${entry.parent}\`; source: \`${entry.module}\` |`)
    : [];
  const configRows = info.configEntries && info.configEntries.length
    ? info.configEntries.map((entry) => `| \`${entry.evidence}\` | ${escapeCell(entry.type)} | 已登记 | ${escapeCell(entry.detail)} |`)
    : [];
  const depRows = info.dependencyEntries && info.dependencyEntries.length
    ? info.dependencyEntries.map((entry) => `| \`${entry.name}\` | ${escapeCell(entry.category)} | 已登记 | ${escapeCell(entry.evidence)} |`)
    : [];
  const optionalDepGroups = info.optionalDeps && info.optionalDeps.length
    ? info.optionalDeps.map((entry) => `| \`${escapeCell(entry.group)}\` | optional dep group | 已登记 | ${entry.deps.slice(0, 6).map((d) => '`' + d + '`').join(', ')}${entry.deps.length > 6 ? ', ...' : ''} (evidence: \`${entry.evidence}\`) |`)
    : [];
  const plannedRows = info.plannedCandidates.length
    ? info.plannedCandidates.map((feature) => `| ${escapeCell(feature.name)} | 待实现 | ${escapeCell(feature.evidence)} | ${escapeCell(feature.boundary || 'Auto-discovered planned/unfinished item; verify scope and owner before implementation.')} |`)
    : ['| - | 待登记 | - | Add planned/unfinished features from roadmap, TODO, or product notes. |'];
  const programLines = programs.length
    ? programs.map((program) => `- Governance: ${program.name} (${program.ref || 'unmapped'}): ${program.description || 'governance program'}`)
    : ['- Governance: add programs with `/ft:init` or `new-node`.'];
  const featureLines = info.featureCandidates.length
    ? info.featureCandidates.flatMap(renderFeatureOverviewLines)
    : ['- Existing feature candidates: 待登记'];
  const plannedLines = info.plannedCandidates.length
    ? info.plannedCandidates.map((feature) => `- Planned/unfinished: ${feature.name} [${feature.type || 'planned'}] (${feature.evidence})`)
    : ['- Planned/unfinished: 待登记'];
  const programTable = programRows.map((row) => `| ${row.map(escapeCell).join(' | ')} |`);

  return [
    '## 注册规则',
    '',
    '- 本文件是项目功能树与功能状态注册表；不要用 issue、PR 或临时报告替代它记录长期功能状态。',
    '- 本文件描述当前/未来项目的功能树：既登记已有功能，也登记计划/未完成功能。',
    '- 本文件是开发者方向指引；新增实现、重构和规划都应回到这里校准，避免方向失联或跑偏。',
    '- 以功能/能力为主线组织内容，再挂接模块、命令、证据和依赖关系。',
    '- 状态建议使用：`已实现`、`部分实现`、`设计中`、`待实现`、`暂停`、`废弃`。',
    '- 使用 `function-tree` skill（function tree）或 `/ft:*` 命令维护治理节点、证据、授权范围和 closeout。',
    '- 生成区可由 `ft-governance.cjs doc --root <repo>` 刷新；长期项目约定写入 project-notes 区块。',
    '',
    '## 功能全景图',
    '',
    `- Project: ${info.name}${info.version ? ` v${info.version}` : ''}`,
    ...(info.languages.length ? [`- Languages: ${info.languages.map((l) => `${l.language} (${l.percentage}%)`).join(', ')}`] : []),
    ...featureLines,
    ...plannedLines,
    ...programLines,
    info.sourceRoots.length ? `- Source roots: ${formatList(info.sourceRoots)}` : '- Source roots: 待登记',
    info.docs.length ? `- Documentation: ${formatList(info.docs)}` : '- Documentation: 待登记',
    '',
    '## 状态注册表',
    '',
    '### 模块/能力节点',
    '',
    '| Node | Type | Status | Evidence / Notes |',
    '|------|------|--------|------------------|',
    `| ${escapeCell(info.name)} | project | 已登记 | HEAD: \`${info.head || 'unknown'}\`; root: \`${root}\` |`,
    ...featureRows,
    ...moduleRows,
    ...sourceRows,
    ...docRows,
    '',
    '### CLI/运营入口节点',
    '',
    '| Command | Purpose | Status | Notes |',
    '|---------|---------|--------|-------|',
    '| `/ft:init` | initialize governance and FUNCTION_TREE files | 已实现 | backs up existing `FUNCTION_TREE.md` before refresh |',
    '| `/ft:status` | show programs and active gates | 已实现 | helper: `status` |',
    '| `/ft:gate` | show current blockers and allowed scope | 已实现 | helper: `gate --verbose` |',
    '| `/ft:observe` | collect baseline evidence | 已实现 | evidence is required before authorization |',
    '| `/ft:authorize` | prepare allowed paths, non-goals, and gates | 已实现 | source edits remain disabled until approval transition |',
    '| `/ft:closeout` | record landed summary and verification gates | 已实现 | close node after review |',
    ...commandRows,
    '',
    '### UI/页面入口节点',
    '',
    '| Route | Source | Status | Notes |',
    '|-------|--------|--------|-------|',
    ...uiRows,
    '',
    '### API/服务入口节点',
    '',
    '| Endpoint | Source | Status | Notes |',
    '|----------|--------|--------|-------|',
    ...apiRows,
    '',
    '### Public API Surface (__all__ exports)',
    '',
    '| Module | Type | Status | Exports / Notes |',
    '|--------|------|--------|-----------------|',
    ...publicApiRows,
    '',
    '### Documentation System',
    '',
    '| System | Type | Status | Notes |',
    '|--------|------|--------|-------|',
    ...docSystemRows,
    '',
    ...(exceptionRows.length ? [
      '### Exception Hierarchy',
      '',
      '| Exception | Type | Status | Notes |',
      '|-----------|------|--------|-------|',
      ...exceptionRows,
      '',
    ] : []),
    ...(configRows.length ? [
      '### Configuration & Environment',
      '',
      '| Entry | Type | Status | Notes |',
      '|-------|------|--------|-------|',
      ...configRows,
      '',
    ] : []),
    ...(depRows.length ? [
      '### Core Dependencies',
      '',
      '| Package | Category | Status | Evidence |',
      '|---------|----------|--------|----------|',
      ...depRows,
      '',
    ] : []),
    ...(optionalDepGroups.length ? [
      '### Optional Dependency Groups',
      '',
      '| Group | Type | Status | Contents |',
      '|-------|------|--------|----------|',
      ...optionalDepGroups,
      '',
    ] : []),
    '### 已设计/待实现节点',
    '',
    '| 功能节点 | 状态 | 证据 | 边界 |',
    '|---|---|---|---|',
    ...plannedRows,
    '',
    '### 治理计划/开放节点',
    '',
    '| Program | FUNCTION_TREE ref | Description | Nodes | Active gates | Tree |',
    '|---------|-------------------|-------------|-------|--------------|------|',
    ...programTable,
    '',
    '## 模块/命令证据展开',
    '',
    ...renderCandidateEvidenceLines(info),
    '- `.governance/programs/<program>/tree.md` records the program entrypoint and FUNCTION_TREE ref.',
    '- `.governance/programs/<program>/nodes.json` records node status, evidence, authorization, and closeout.',
    '- `.governance/programs/<program>/cards/*.yaml` stores generated authorization task cards.',
    '- `.governance/active-gates.json` and `.governance/active-gates.md` summarize currently open gates.',
    '',
    '## CLI 命令证据展开',
    '',
    '- `/ft:new-node <program> <node-id>` creates a planning node.',
    '- `/ft:observe <program> <node-id> --evidence <path-or-note>` records evidence at current HEAD.',
    '- `/ft:transition <program> <node-id> --to <status>` enforces the legal state machine.',
    '- `/ft:implement` runs `scope-check` against active authorization.',
    '- `/ft:doc` refreshes this document and creates backups when content changes.',
    '',
    '## 模块依赖关系',
    '',
    '- `FUNCTION_TREE.md` is the human-readable feature tree and status registry.',
    '- `.governance/active-gates.json` feeds active gate summaries and scope checks.',
    '- `.governance/programs/*/nodes.json` feeds node state, task cards, and closeout history.',
    '- Source modules and CLI entries should be attached to feature nodes as evidence is collected.',
    '',
    '## 更新日志',
    '',
    `- Initialized by function-tree for ${logProgram} (${logRef}).`,
    '',
    '## 开放事项',
    '',
    '- Replace placeholder rows with project-specific capability nodes.',
    '- Add source-module evidence as nodes move through observe and authorize gates.',
    '- Add dependency notes when feature ownership spans multiple modules or commands.',
    '',
    '## 维护规则',
    '',
    '- Keep generated governance state in `.governance/`; keep durable project conventions in project notes.',
    '- Backups of prior `FUNCTION_TREE.md` files are stored under `.governance/backups/`.',
    '- Do not hand-edit generated active gate markdown; change node state through the helper.',
  ].join('\n');
}
module.exports = { refreshFunctionTreeDoc, writeFunctionTreeDoc, backupFunctionTreeDoc, extractProjectNotes, extractExistingFunctionTreeBody, extractPreservedPreviousFunctionTree, stripGeneratedFunctionTreeSection, stripFunctionTreeTitle, stripGeneratedDocPreamble, looksLikeFunctionTreeBody, isRefreshableGeneratedFunctionTreeBody, defaultProjectNotes, renderFunctionTreeDoc, renderDefaultFunctionTreeBody };
